### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by olesh0** [ivanstan/tle-api#170]
Tried making requests to this API, but I'm being blocked by CORS policy (the problem is definitely not with my application).

P.S. I can see in the commits history that you tried to setup CORS rules (couple days ago), but it seems like it didn't quite worked out :(

P.S. №2 Commit a842aeda3febd2f7bfa7b5116b06fc81a4760e2b says it was 4 days ago, so may be it's not yet deployed :(

**Comment by ivanstan** [comment]
Thanks for reporting this issue, and sorry for the late response. CORS header is now present it has been added on web server level.
